import type { Metadata } from "next";
import HeadBar from "@/components/HeadBar";
import FooterSection from "@/components/FooterSection";
import "./globals.css";
import "@flaticon/flaticon-uicons/css/all/all.css"

export const metadata: Metadata = {
  title: "موکا چاپ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`antialiased`}
      >
        <HeadBar />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
